version: '3.8'

services:
  app1:
    build:
      context: ./app
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  app2:
    build:
      context: ./app
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./app/index.html:/usr/share/nginx/html/index.html





