version: '3.8'

services:
  app1:
    build:
      context: ./app1
    image: app1_image:latest
    volumes:
      - app1-data:/var/www/html
    networks:
      - my-network

  app2:
    build:
      context: ./app2
    image: app2_image:latest
    volumes:
      - ./app2:/var/www/html
    networks:
      - my-network

  # Primera instancia de app3
  app3_instance1:
    build:
      context: ./app3
    image: app3_image:latest
    environment:
      - APP_MODE=version2.0
    networks:
      - my-network

  # Segunda instancia de app3
  app3_instance2:
    build:
      context: ./app3
    image: app3_image:latest
    environment:
      - APP_MODE=version2.0
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
    image: nginx_image:latest
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3_instance1
      - app3_instance2
    networks:
      - my-network

volumes:
  app1-data:

networks:
  my-network:
    driver: bridge























