version: '3.8'

services:
  app1:
    build:
      context: ./app1
    image: app1_image:latest
    volumes:
      - app1-data:/var/www/html
    networks:
      - my-network

  app2:
    build:
      context: ./app2
    image: app2_image:latest
    volumes:
      - ./app2:/var/www/html
    networks:
      - my-network

  app3:
    build:
      context: ./app3
    image: app3_image:latest
    volumes:
      - ./mock-data:/usr/src/app/mock-data
    environment:
      - APP_MODE=${APP_MODE}
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
    image: nginx_image:latest
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - my-network

volumes:
  app1-data:

networks:
  my-network:
    driver: bridge





















