version: '3.8'

services:
  app1:
    build:
      context: ./app
    container_name: app1
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  app2:
    build:
      context: ./app
    container_name: app2
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2








