version: '3.8'

services:
  app1:
    build:
      context: ./app1
    image: app1_image:latest
    user: "1001:1001" # Non-root user
    ports:
      - "3001:80"
    networks:
      - app_network

  app2:
    build:
      context: ./app2
    image: app2_image:latest
    user: "1001:1001" # Non-root user
    ports:
      - "3002:80"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
    image: nginx_image:latest
    ports:
      - "443:443"
    networks:
      - app_network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro

networks:
  app_network:
    driver: bridge




















